version: "1.0"
info:
  model: int-scaffold
packages:
- name: As_doctor_botProject
  gitServerName: avivsimds_github
  gitUrl: https://github.com/AvivSimDS
  gitUsername: AvivSimDS
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.as_doctor_bot.integrations:HMO_UPDATE_MEHEDET
  packages:
  - name: As_doctor_botProject
    version: "1.0"
- serviceName: project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:InsertInterviewDetails
  packages:
  - name: As_doctor_botProject
    version: "1.0"
configurationVariables:
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.networkProtocol
  : tcp
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.password
  : "{AES}PTWq2hgg4RimZ8H0r79NmA=="
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.serverName
  : 10.240.64.29
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.poolable
  : "false"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.driverType
  : mysql_connector_java_8023
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.dbType
  : MySQL
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.trustStore
  : ""
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionEnabled
  : "false"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.databaseName
  : InfermedicaDB
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.portNumber
  : "3306"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.user
  : wmuser
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.As_doctor_botProject.project.as_doctor_bot.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.as_hmo_meu_db.connectionSettings.keyStore
  : ""
